dataset:
  name: celeba

model:
  image_size: 256
  timesteps: 1000
  first_layer_channels: 128
  channels_multiplier: [1, 1, 2, 2, 4, 4]
  num_res_blocks: 2
  attn_resolutions: [16]
  dropout: 0

training:
  batch_size: 16
  view_sample_size: 10
  num_workers: 8
  max_steps: 500000
  learning_rate: 2e-5
  warmup_steps: 5000
  log_interval: 200
  results_folder: "."
  accelerator: "gpu"
  num_gpus: 4
  gradient_clip_val: 1.0