dataset:
  name: cifar10

model:
  image_size: 32
  timesteps: 1000
  first_layer_channels: 128
  channels_multiplier: [1, 2, 2, 2]
  num_res_blocks: 2
  attn_resolutions: [16]
  dropout: 0.1

training:
  batch_size: 128
  view_sample_size: 10
  num_workers: 8
  max_steps: 800000
  learning_rate: 2e-4
  warmup_steps: 5000
  log_interval: 100
  results_folder: "."
  accelerator: "gpu"
  num_gpus: 1
  gradient_clip_val: 1.0